"""OneNote Notebook Organizer -- creates index pages and organized structure.

Run once to populate the new organizational sections with index/summary pages.
Uses inline HTML only (no block-level tags) since OneNote T elements only
support inline formatting inside CDATA.
"""

import sys
import re
import xml.etree.ElementTree as ET

sys.path.insert(0, ".")
from onenote_lib import com_client
from onenote_lib.xml_parser import parse_notebooks

# OneNote XML namespace
NS = "http://schemas.microsoft.com/office/onenote/2013/onenote"

# Section IDs
SECTIONS = {
    "_Index": "{9B939CCB-C163-4957-BC87-CAB01BFDA076}{1}{B0}",
    "_Networking": "{90E22DAF-D3AF-484E-B11E-0246DEAD9671}{1}{B0}",
    "_Programming": "{ED21DD7A-1B0C-4BBD-9187-33FB52A38CE8}{1}{B0}",
    "_Cybertron_Infra": "{BEB1D1A6-8432-470F-A679-7853C53C68D1}{1}{B0}",
    "_Career": "{6AD896F9-37C7-421E-B4BB-1B8FE8DEBC0E}{1}{B0}",
}

NB1_ID = "{44B98C82-9DC5-4FB0-AB34-F4C654E32241}{1}{B0}"
NB2_ID = "{5F6337CE-912C-42EC-A3BE-72B8803ADA86}{1}{B0}"

# Formatting helpers
H1 = 'style="font-size:18pt;font-weight:bold"'
H2 = 'style="font-size:14pt;font-weight:bold"'
H3 = 'style="font-size:12pt;font-weight:bold"'
GRAY = 'style="color:#888888"'
MONO = 'style="font-family:Consolas"'
BR = "<br>"
BR2 = "<br><br>"
INDENT = "&nbsp;&nbsp;&nbsp;&nbsp;"


def create_page(section_id: str, title: str, body: str) -> str:
    """Create a page with inline HTML content."""
    page_id = com_client.create_new_page(section_id)
    page_xml = com_client.get_page_content(page_id)
    root = ET.fromstring(page_xml)
    page_id_attr = root.get("ID")

    oe_match = re.search(r'<one:OE\s+([^>]+)>', page_xml)
    oe_raw = oe_match.group(1) if oe_match else ""
    oe_raw = re.sub(r'objectID="[^"]*"', '', oe_raw).strip()

    xml = (
        f'<?xml version="1.0" encoding="utf-8"?>'
        f'<one:Page xmlns:one="http://schemas.microsoft.com/office/onenote/2013/onenote" '
        f'ID="{page_id_attr}">'
        f'<one:Title lang="en-US">'
        f'<one:OE {oe_raw}>'
        f'<one:T><![CDATA[{title}]]></one:T>'
        f'</one:OE></one:Title>'
        f'<one:Outline><one:OEChildren><one:OE>'
        f'<one:T><![CDATA[{body}]]></one:T>'
        f'</one:OE></one:OEChildren></one:Outline>'
        f'</one:Page>'
    )

    com_client.update_page_content(xml)
    return page_id_attr


def get_hierarchy():
    xml = com_client.get_hierarchy("", com_client.PAGES)
    return parse_notebooks(xml)


# =====================================================================
# Page builders
# =====================================================================


def create_master_index():
    print("Creating master index...")
    notebooks = get_hierarchy()

    b = f'<span {H1}>Wylvek\'s OneNote -- Master Index</span>{BR}'
    b += f'<span {GRAY}><i>Auto-generated by Megatron2 (2026-02-27). Maps every section and page across both notebooks.</i></span>{BR2}'

    b += f'<span {H2}>[*] New Organized Sections</span>{BR}'
    b += f'{INDENT}<b>_Index</b> -- You are here. Master table of contents.{BR}'
    b += f'{INDENT}<b>_Networking</b> -- Cisco, Palo Alto, ForcePoint, UniFi, firewalls, VPN, protocols{BR}'
    b += f'{INDENT}<b>_Programming</b> -- Python, PowerShell, CMD/batch, Docker, sed, pip, scripting{BR}'
    b += f'{INDENT}<b>_Cybertron_Infra</b> -- TrueNAS, Vault, RustDesk, Git, Home Assistant, infrastructure{BR}'
    b += f'{INDENT}<b>_Career</b> -- Resume, timecards, certifications, HR/benefits{BR2}'

    for nb in notebooks:
        b += f'<span {H2}>{nb.name}</span>{BR}'
        for sec in nb.sections:
            if sec.name.startswith("_"):
                continue
            pc = len(sec.pages)
            if pc == 0:
                b += f'{INDENT}<b>{sec.name}</b> <span {GRAY}>(empty)</span>{BR}'
                continue
            b += f'{INDENT}<b>{sec.name}</b> ({pc} page{"s" if pc != 1 else ""}){BR}'
            for p in sec.pages[:6]:
                lvl_indent = INDENT * 2 + ("&nbsp;&nbsp;" * max(0, p.level - 1))
                mod = p.last_modified[:10] if p.last_modified else "?"
                b += f'{lvl_indent}-- {p.name} <span {GRAY}>[{mod}]</span>{BR}'
            if pc > 6:
                b += f'{INDENT * 2}<i>... and {pc - 6} more pages</i>{BR}'
        b += BR

    b += f'<span {H2}>Organization Notes</span>{BR}'
    b += f'The new underscore-prefixed sections contain <b>consolidated summaries</b> '
    b += f'of content scattered across the original sections. The original sections and pages are untouched -- '
    b += f'nothing was deleted or moved.{BR2}'
    b += f'The Quick Notes section had 43 pages covering networking, programming, AI, credentials, and personal items. '
    b += f'The new sections provide organized entry points to find content by topic.{BR2}'
    b += f'<b>Sections that could be archived:</b> compusharecontact (1 untitled page from 2017), '
    b += f'From_thedose (2 untitled pages), Unity Game Dev (1 page from 2019), BeagleBone (1 page from 2020), '
    b += f'Holiday Gifts (Christmas 2020 only).{BR}'

    create_page(SECTIONS["_Index"], "Master Index - Table of Contents", b)
    print("  Done")


def create_networking_index():
    print("Creating networking index...")

    b = f'<span {H1}>Networking Reference Index</span>{BR}'
    b += f'<span {GRAY}><i>Consolidated index of all networking-related pages across both notebooks.</i></span>{BR2}'

    b += f'<span {H2}>Cisco (Routing / Switching / Collaboration)</span>{BR}'
    b += f'{INDENT}<b>Cisco</b> (12K chars) -- Ping characters, IOS commands, comprehensive reference. In <i>Quick Notes</i>.{BR}'
    b += f'{INDENT}<b>Collaboration services</b> -- Cisco Meeting Server upgrade notes. In <i>Quick Notes</i>.{BR}'
    b += f'{INDENT}<b>Vpc vs trunks</b> -- Nexus vPC vs regular trunks comparison. In <i>Quick Notes</i>.{BR}'
    b += f'{INDENT}<b>ISE WEBX info</b> -- Cisco ISE v4.0 training schedule. In <i>Quick Notes</i>.{BR}'
    b += f'{INDENT}<b>Cisco Learning Network info</b> -- Certification team contacts. In <i>Quick Notes</i>.{BR}'
    b += f'{INDENT}<b>cMNL Class</b> section -- DCNM discovery labs (6 pages). In <i>Wylvek\'s Notebook</i>.{BR2}'

    b += f'<span {H2}>Palo Alto / Firewall / Security</span>{BR}'
    b += f'{INDENT}<b>Palo Alto</b> (22K chars) -- PAN-OS packet flow, Day in Life of a Packet. In <i>Quick Notes</i>.{BR}'
    b += f'{INDENT}<b>PaloAlto Packet Flow</b> -- Diagram image. In <i>Quick Notes</i>.{BR}'
    b += f'{INDENT}<b>Bfd f5 palo alto</b> (36K chars, 32 imgs) -- BFD protocol deep-dive with F5. In <i>Quick Notes</i>.{BR}'
    b += f'{INDENT}<b>ForcePoint</b> -- ForcePoint linux shell access. In <i>Quick Notes</i>.{BR}'
    b += f'{INDENT}<b>Risk determination commands</b> -- Linux security assessment commands. In <i>Quick Notes</i>.{BR}'
    b += f'{INDENT}<b>USG firewall notes</b> -- UniFi Security Gateway rules. In <i>network stuff</i> (3734).{BR}'
    b += f'{INDENT}<b>Windows firewall Track activity</b> -- Firewall log analysis. In <i>network stuff</i> (3734).{BR}'
    b += f'{INDENT}<b>Sec+ notes</b> -- Security+ study notes. In <i>random notes</i>.{BR2}'

    b += f'<span {H2}>UniFi / Home Network</span>{BR}'
    b += f'{INDENT}<b>Unifi info</b> -- Controller config, updated 2026-01-28. In <i>network stuff</i> (3734).{BR}'
    b += f'{INDENT}{INDENT}Subpages: Url codes, Udm commands, ESXI/RHEL, Commands, Controller stop service, AP LED flash codes{BR}'
    b += f'{INDENT}<b>NetDuma</b> -- Gaming router config. In <i>network stuff</i> (3734).{BR}'
    b += f'{INDENT}<b>Pi Hole</b> -- DNS ad blocking. In <i>network stuff</i> (3734).{BR}'
    b += f'{INDENT}<b>Gaming configs</b> -- Network gaming optimization. In <i>network stuff</i> (3734).{BR}'
    b += f'{INDENT}<b>Windows networking</b> -- Windows network config. In <i>network stuff</i> (3734).{BR}'
    b += f'{INDENT}<b>Legacy network info</b> -- Old network config. In <i>infrastructure_tech</i> (3734).{BR2}'

    b += f'<span {H2}>General Networking</span>{BR}'
    b += f'{INDENT}<b>Web Notes</b> (7K chars, 6 imgs) -- TCP port forwarding, netsh portproxy. In <i>Quick Notes</i>.{BR}'
    b += f'{INDENT}<b>Linux IP Troubleshooting</b> -- WireGuard MTU fix (1412). In <i>Quick Notes</i>.{BR}'
    b += f'{INDENT}<b>VM ware esxi vmnic vswitch</b> -- ESXi network diagrams (3 imgs). In <i>Quick Notes</i>.{BR}'
    b += f'{INDENT}<b>NETWORK_REL</b> -- Network relationship diagram. In <i>PAXPATRIS</i>.{BR2}'

    b += f'<span {H2}>Quick Reference</span>{BR}'
    b += f'<b>Cisco Ping Characters:</b> ! = reply, . = timeout, U = unreachable, Q = source quench, M = can\'t fragment{BR}'
    b += f'<b>Port Proxy:</b> <span {MONO}>netsh interface portproxy add v4tov4 listenport=4422 listenaddress=x connectport=80 connectaddress=y</span>{BR}'
    b += f'<b>vPC vs Trunks:</b> vPC on Nexus provides active-active redundancy, load balancing, eliminates STP blocked ports{BR}'
    b += f'<b>WireGuard MTU:</b> Add MTU = 1412 to /etc/wireguard/wg0.conf{BR}'

    create_page(SECTIONS["_Networking"], "Networking Reference Index", b)
    print("  Done")


def create_programming_index():
    print("Creating programming index...")

    b = f'<span {H1}>Programming and Scripting Reference</span>{BR}'
    b += f'<span {GRAY}><i>Consolidated index of all programming/scripting content across both notebooks.</i></span>{BR2}'

    b += f'<span {H2}>Python</span>{BR}'
    b += f'{INDENT}<b>python</b> (17K chars) -- Virtual envs, subprocess, file handling, comprehensive ref. In <i>Quick Notes</i>.{BR}'
    b += f'{INDENT}<b>Functions n stuff</b> -- Windows path normalization, utilities. In <i>Quick Notes</i> (subpage of python).{BR}'
    b += f'{INDENT}<b>pip</b> -- Package management, bulk downloads, wheel files. In <i>Quick Notes</i>.{BR}'
    b += f'{INDENT}<b>Python Stuff</b> -- General Python notes. In <i>Misc_Tech_stuff</i> (3734).{BR}'
    b += f'{INDENT}<b>import subprocess</b> -- LLM-controlled command execution snippet. In <i>Quick Notes</i>.{BR}'
    b += f'{INDENT}<b>PDF issues</b> -- NLP libraries for PDF processing (NLTK, SpaCy, HuggingFace). In <i>Quick Notes</i>.{BR2}'

    b += f'<span {H2}>PowerShell and CMD</span>{BR}'
    b += f'{INDENT}<b>Powershell notes</b> (5K chars) -- Test-NetConnection, tracing, network diagnostics. In <i>Quick Notes</i>.{BR}'
    b += f'{INDENT}<b>Windows command line</b> -- Netstat, robocopy commands. In <i>Quick Notes</i>.{BR}'
    b += f'{INDENT}<b>CMD and batch</b> -- Virtual env creation, doskey history, batch scripting. In <i>Quick Notes</i>.{BR}'
    b += f'{INDENT}<b>Windows Trace</b> -- Service Trace Viewer (SvcTraceViewer.exe). In <i>Quick Notes</i>.{BR}'
    b += f'{INDENT}<b>No admin installs</b> -- .NET without admin rights. In <i>Quick Notes</i>.{BR2}'

    b += f'<span {H2}>Linux</span>{BR}'
    b += f'{INDENT}<b>sed</b> -- Regex for IP extraction from files. In <i>Quick Notes</i>.{BR}'
    b += f'{INDENT}<b>Linux Sacra</b> -- Linux commands reference. In <i>Misc_Tech_stuff</i> (3734).{BR}'
    b += f'{INDENT}<b>Centos</b> -- CentOS-specific notes. In <i>Misc_Tech_stuff</i> (3734).{BR2}'

    b += f'<span {H2}>Docker</span>{BR}'
    b += f'{INDENT}<b>Docker cheat sheet</b> -- 9 reference images. In <i>Quick Notes</i>.{BR}'
    b += f'{INDENT}<b>Docker</b> -- Docker reference (updated 2026-02-05). In <i>Misc_Tech_stuff</i> (3734).{BR}'
    b += f'{INDENT}<b>Open webui</b> -- Docker compose for Open WebUI. In <i>Misc_Tech_stuff</i> (3734, subpage of Docker).{BR2}'

    b += f'<span {H2}>Other Tools</span>{BR}'
    b += f'{INDENT}<b>VLC NOTES</b> -- Screen casting, recording settings. In <i>Quick Notes</i>.{BR}'
    b += f'{INDENT}<b>VISIO visio</b> -- Font changes, developer mode. In <i>Quick Notes</i>.{BR}'
    b += f'{INDENT}<b>Web Scraping</b> -- Web scraping techniques. In <i>Misc_Tech_stuff</i> (3734).{BR}'
    b += f'{INDENT}<b>Acronis</b> / <b>Acronis info</b> -- Backup software. In <i>Software</i> and <i>Misc_Tech_stuff</i>.{BR2}'

    b += f'<span {H2}>Quick Reference</span>{BR}'
    b += f'<b>Python venv:</b> <span {MONO}>"C:\\Program Files\\Python310\\python.exe" -m venv .name_of_env</span>{BR}'
    b += f'<b>Robocopy:</b> <span {MONO}>robocopy "source" "dest" /E /J /MOVE /XO /MT:8</span>{BR}'
    b += f'<b>Pip bulk:</b> <span {MONO}>pip download -r requirements.txt -d ./wheels</span>{BR}'
    b += f'<b>sed IP:</b> <span {MONO}>sed -n \'/[0-9]\\{{1,3\\}}\\.[0-9]\\{{1,3\\}}\\.[0-9]\\{{1,3\\}}\\.[0-9]\\{{1,3\\}}/p\' file.txt</span>{BR}'
    b += f'<b>.NET no admin:</b> <span {MONO}>set DOTNET_ROOT=%USERPROFILE%\\dotnet</span>{BR}'

    create_page(SECTIONS["_Programming"], "Programming and Scripting Reference", b)
    print("  Done")


def create_cybertron_index():
    print("Creating Cybertron infra index...")

    b = f'<span {H1}>Cybertron Infrastructure Reference</span>{BR}'
    b += f'<span {GRAY}><i>All home lab / Cybertron network infrastructure notes from across both notebooks.</i></span>{BR2}'

    b += f'<span {H2}>Core Infrastructure</span>{BR}'
    b += f'{INDENT}<b>Truenas</b> -- TrueNAS configuration. In <i>infrastructure_tech</i> (3734). Updated 2026-02-16.{BR}'
    b += f'{INDENT}<b>Home Assistant</b> -- Smart home hub config. In <i>infrastructure_tech</i> (3734). Updated 2026-01-28.{BR}'
    b += f'{INDENT}{INDENT}Subpage: <b>Tasmota</b> -- IoT device flashing.{BR}'
    b += f'{INDENT}<b>Megatron</b> -- Primary workstation notes. In <i>infrastructure_tech</i> (3734).{BR}'
    b += f'{INDENT}<b>Unifi info</b> -- Network controller. In <i>network stuff</i> (3734). Updated 2026-01-28.{BR2}'

    b += f'<span {H2}>Cybertron Services (from AI_stuff)</span>{BR}'
    b += f'{INDENT}<b>vault</b> -- HashiCorp Vault credentials/config. Updated 2026-02-08.{BR}'
    b += f'{INDENT}<b>Rustdesk</b> -- Self-hosted remote desktop passwords. Updated 2026-02-06.{BR}'
    b += f'{INDENT}<b>Git</b> -- Git credentials and screenshots. Updated 2026-02-16.{BR}'
    b += f'{INDENT}<b>Openclaw</b> (9K chars) -- OpenClaw gateway config/usage. Updated 2026-02-17.{BR}'
    b += f'{INDENT}<b>Discord</b> -- Bot tokens.{BR}'
    b += f'{INDENT}<b>Things I want in cybertron</b> -- Feature wishlist. Updated 2026-02-16.{BR2}'

    b += f'<span {H2}>Raspberry Pi / Legacy Projects</span>{BR}'
    b += f'{INDENT}<b>pi</b> section -- Updating, webcam setup. In <i>Wylvek\'s Notebook</i>.{BR}'
    b += f'{INDENT}<b>BeagleBone</b> section -- BeagleBone Black. In <i>Wylvek\'s Notebook</i>.{BR}'
    b += f'{INDENT}<b>OctoPrint</b> -- 3D printer server. In <i>infrastructure_tech</i> (3734).{BR}'
    b += f'{INDENT}<b>Mine Craft Pi</b> -- Minecraft on RPi. In <i>infrastructure_tech</i> (3734).{BR}'
    b += f'{INDENT}<b>PullyPi</b> -- Pi project. In <i>infrastructure_tech</i> (3734).{BR}'
    b += f'{INDENT}<b>Element14 RPi Node Red Alexa</b> -- IoT automation. In <i>infrastructure_tech</i> (3734).{BR}'
    b += f'{INDENT}<b>FAUXMO</b> -- Amazon Echo emulator. In <i>Misc_Tech_stuff</i> (3734).{BR2}'

    b += f'<span {H2}>Windows Management</span>{BR}'
    b += f'{INDENT}<b>Windows genera</b> -- General Windows tips. In <i>Misc_Tech_stuff</i> (3734).{BR}'
    b += f'{INDENT}<b>windows</b> -- Robocopy, disk space, PowerShell. In <i>Quick Notes</i>.{BR}'
    b += f'{INDENT}<b>Windows Sacra</b> -- Windows sacred knowledge. In <i>Misc_Tech_stuff</i> (3734).{BR}'
    b += f'{INDENT}<b>Gpu windows troubleshooting</b> -- GPU issues. In <i>random notes</i>.{BR2}'

    b += f'<span {H2}>Other</span>{BR}'
    b += f'{INDENT}<b>HD_homerun</b> -- TV tuner device. In <i>Misc_Tech_stuff</i> (3734).{BR}'
    b += f'{INDENT}<b>Spark40</b> -- Guitar amp connectivity. In <i>Misc_Tech_stuff</i> (3734).{BR}'
    b += f'{INDENT}<b>AirQuality</b> section -- TVOCs and CO2 monitoring. In <i>3734 Network_Notes</i>.{BR}'
    b += f'{INDENT}<b>NETWORK_REL</b> -- Network topology. In <i>PAXPATRIS</i>.{BR}'
    b += f'{INDENT}<b>USB drive notes</b> -- USB config. In <i>Misc_Tech_stuff</i> (3734).{BR}'
    b += f'{INDENT}<b>Splashtop info</b> -- Old remote desktop. In <i>infrastructure_tech</i> (3734).{BR}'

    create_page(SECTIONS["_Cybertron_Infra"], "Cybertron Infrastructure Reference", b)
    print("  Done")


def create_career_index():
    print("Creating career index...")

    b = f'<span {H1}>Career and Professional Reference</span>{BR}'
    b += f'<span {GRAY}><i>Resume, certifications, timecards, and HR/benefits documentation.</i></span>{BR2}'

    b += f'<span {H2}>Resume and Profile</span>{BR}'
    b += f'{INDENT}<b>Resume 2021</b> (12K chars) -- Full resume with clearance info, CCNA/CCNP. In <i>Quick Notes</i>.{BR}'
    b += f'{INDENT}<b>Things to incorporate into new resume</b> -- Resume notes. In <i>resume notes</i> section.{BR}'
    b += f'{INDENT}Updated resume (2024): Thomaswg_resume2024_with_months.docx in OneDrive Documents.{BR2}'

    b += f'<span {H2}>Certifications</span>{BR}'
    b += f'{INDENT}<b>CISSP</b> section -- Full bootcamp notes (Mon-Thu) plus 56-page course review. In <i>Wylvek\'s Notebook</i>.{BR}'
    b += f'{INDENT}<b>Sec+ notes</b> -- Security+ study notes. In <i>random notes</i>.{BR}'
    b += f'{INDENT}<b>Cisco Learning Network info</b> -- Certification contacts. In <i>Quick Notes</i>.{BR}'
    b += f'{INDENT}<b>cMNL Class</b> section -- Cisco DCNM lab discoveries (6 pages). In <i>Wylvek\'s Notebook</i>.{BR2}'

    b += f'<span {H2}>Timecards and HR</span>{BR}'
    b += f'{INDENT}<b>Deltek info</b> -- Timecard query syntax. In <i>Quick Notes</i>.{BR}'
    b += f'{INDENT}<b>Timecards</b> -- October 2025 notes. In <i>october_2025</i> section.{BR}'
    b += f'{INDENT}<b>Caci_tc automation</b> -- Playwright + Node.js timecard bot. In <i>AI_stuff</i>.{BR}'
    b += f'{INDENT}<b>Web automations</b> -- Timecard web element selectors. In <i>AI_stuff</i>.{BR}'
    b += f'{INDENT}<b>Health plans comparison</b> -- CareFirst benefits analysis. In <i>Quick Notes</i> (long title).{BR2}'

    b += f'<span {H2}>Security Clearance</span>{BR}'
    b += f'{INDENT}<b>2022 e-qip</b> -- eQIP security clearance form. In <i>tax docs</i> section.{BR2}'

    b += f'<span {H2}>Work Tools</span>{BR}'
    b += f'{INDENT}<b>Tech_Notes</b> section -- Tools, remotes, file transfers, Cisco tweaks, updates. 5 pages.{BR}'
    b += f'{INDENT}<b>School stuff</b> section -- HP info (updated 2026-01) + old Mesh V rails docs.{BR}'

    create_page(SECTIONS["_Career"], "Career and Professional Reference", b)
    print("  Done")


def create_ai_ml_index():
    print("Creating AI/ML index...")
    ai_section_id = "{6CC1B568-8CCF-0183-3FBF-18C3141471FB}{1}{B0}"

    b = f'<span {H1}>AI and Machine Learning -- Section Index</span>{BR}'
    b += f'<span {GRAY}><i>Index of all 24 pages in this section, organized by topic.</i></span>{BR2}'

    b += f'<span {H2}>Cybertron / Infrastructure (also indexed in _Cybertron_Infra)</span>{BR}'
    b += f'{INDENT}<b>vault</b> -- Vault credentials display{BR}'
    b += f'{INDENT}<b>Rustdesk</b> -- RustDesk password table{BR}'
    b += f'{INDENT}<b>Git</b> -- Git credentials + screenshots{BR}'
    b += f'{INDENT}<b>Openclaw</b> (9K chars) -- OpenClaw gateway setup and usage{BR}'
    b += f'{INDENT}<b>Discord</b> -- Bot token{BR}'
    b += f'{INDENT}<b>Things I want in cybertron</b> -- Feature wishlist{BR2}'

    b += f'<span {H2}>AI Tools and Frameworks</span>{BR}'
    b += f'{INDENT}<b>Claw alts</b> (34K chars) -- Comprehensive OpenClaw alternatives comparison{BR}'
    b += f'{INDENT}<b>ML sauce pot</b> -- Mixed ML links and Guacamole setup{BR}'
    b += f'{INDENT}<b>ollama</b> -- LLocalSearch + Ollama setup{BR}'
    b += f'{INDENT}<b>tgwebui</b> -- Text Generation WebUI link{BR}'
    b += f'{INDENT}<b>autogenstudio</b> -- AutoGen Studio setup notes{BR}'
    b += f'{INDENT}<b>Open-webui</b> -- Docker update procedure{BR}'
    b += f'{INDENT}<b>Crawl4ai</b> -- Web crawler Docker command{BR}'
    b += f'{INDENT}<b>Qdrant rag streamlit</b> -- RAG pipeline with Qdrant + Streamlit{BR2}'

    b += f'<span {H2}>Research and Learning</span>{BR}'
    b += f'{INDENT}<b>LLM video</b> (77K chars!) -- Full academic paper on multi-modal LLMs{BR}'
    b += f'{INDENT}<b>Conclusons</b> -- Multimodal foundation model concepts{BR}'
    b += f'{INDENT}<b>Simulating Network Infrastructure</b> -- White paper on virtual network dev{BR}'
    b += f'{INDENT}<b>Text Paraphrasing</b> -- Google Colab + CrewAI link{BR2}'

    b += f'<span {H2}>Agent Development</span>{BR}'
    b += f'{INDENT}<b>Desktop agent notes SAVI</b> -- Agent architecture (audio/video I/O, memory, tools){BR}'
    b += f'{INDENT}<b>Agent_zero</b> -- Agent Zero conda env setup{BR}'
    b += f'{INDENT}<b>Anthropic computer use</b> -- Docker command for Anthropic computer use{BR}'
    b += f'{INDENT}<b>jupyter</b> -- JupyterLab + Anaconda env setup{BR2}'

    b += f'<span {H2}>Timecard Automation</span>{BR}'
    b += f'{INDENT}<b>Web automations</b> -- Timecard web element selectors + screenshots{BR}'
    b += f'{INDENT}<b>Caci_tc automation</b> -- Playwright + Node.js setup{BR}'

    create_page(ai_section_id, "AI and ML -- Section Index", b)
    print("  Done")


def create_quick_notes_index():
    print("Creating Quick Notes index...")
    qn_id = "{07D75124-FAD0-08CE-1D52-DF726D7CBF59}{1}{B0}"

    b = f'<span {H1}>Quick Notes -- Section Index</span>{BR}'
    b += f'<span {GRAY}><i>This section has 43 pages. Here is what is in them, organized by topic.</i></span>{BR2}'

    b += f'<span {H2}>Networking and Security (see also: _Networking)</span>{BR}'
    b += f'{INDENT}Risk determination commands -- Linux security commands{BR}'
    b += f'{INDENT}Web Notes (7K, 6 imgs) -- TCP port forwarding, proxying{BR}'
    b += f'{INDENT}ISE WEBX info -- Cisco ISE training schedule{BR}'
    b += f'{INDENT}Cisco Learning Network info -- Certification contacts{BR}'
    b += f'{INDENT}Linux IP Troubleshooting -- WireGuard MTU fix{BR}'
    b += f'{INDENT}Palo Alto (22K) -- PAN-OS packet flow, config{BR}'
    b += f'{INDENT}PaloAlto Packet Flow -- Diagram image{BR}'
    b += f'{INDENT}Cisco (12K) -- Ping characters, IOS commands{BR}'
    b += f'{INDENT}Collaboration services -- Cisco Meeting Server upgrade{BR}'
    b += f'{INDENT}Vpc vs trunks -- Nexus vPC explanation{BR}'
    b += f'{INDENT}Bfd f5 palo alto (36K, 32 imgs) -- BFD protocol deep-dive{BR}'
    b += f'{INDENT}VM ware esxi vmnic vswitch -- ESXi diagrams{BR2}'

    b += f'<span {H2}>Programming and Scripting (see also: _Programming)</span>{BR}'
    b += f'{INDENT}VLC NOTES -- Screen casting setup{BR}'
    b += f'{INDENT}Windows command line -- Netstat, robocopy{BR}'
    b += f'{INDENT}Powershell notes (5K) -- Network diagnostics{BR}'
    b += f'{INDENT}CMD and batch -- Virtual envs, doskey history{BR}'
    b += f'{INDENT}python (17K) -- Comprehensive Python reference{BR}'
    b += f'{INDENT}Functions n stuff -- Python utility functions{BR}'
    b += f'{INDENT}sed -- IP regex extraction{BR}'
    b += f'{INDENT}pip -- Package management{BR}'
    b += f'{INDENT}PDF issues -- NLP libraries for PDFs{BR}'
    b += f'{INDENT}Windows Trace -- Service trace viewer{BR}'
    b += f'{INDENT}No admin installs -- .NET without admin{BR}'
    b += f'{INDENT}Docker cheat sheet -- 9 reference images{BR}'
    b += f'{INDENT}VISIO visio -- Visio developer mode tips{BR}'
    b += f'{INDENT}import subprocess / cmd_output -- Python snippets{BR2}'

    b += f'<span {H2}>Career and Work (see also: _Career)</span>{BR}'
    b += f'{INDENT}Resume 2021 (12K) -- Full resume{BR}'
    b += f'{INDENT}Deltek info -- Timecard queries{BR}'
    b += f'{INDENT}Health plans comparison -- CareFirst benefits analysis{BR}'
    b += f'{INDENT}ForcePoint -- Account info{BR2}'

    b += f'<span {H2}>Credentials and Accounts</span>{BR}'
    b += f'{INDENT}Openai, huggingface -- API keys (HuggingFace, Pinecone){BR}'
    b += f'{INDENT}Voces magicae -- Docker Hub credentials{BR}'
    b += f'{INDENT}Meta pass -- Meta account passwords (7 images){BR}'
    b += f'{INDENT}windows -- Disk space + various system info{BR2}'

    b += f'<span {H2}>Misc / Personal</span>{BR}'
    b += f'{INDENT}kar\'tayl -- Mandalorian language note{BR}'
    b += f'{INDENT}Lexica Nova -- White paper template about VLANs{BR}'
    b += f'{INDENT}POSTS Prism -- Philosophical writing exercise{BR}'
    b += f'{INDENT}Flexible research group -- Just a URL{BR}'
    b += f'{INDENT}Untitled page -- Empty{BR}'

    create_page(qn_id, "Quick Notes -- Section Index", b)
    print("  Done")


def create_nb2_index():
    print("Creating 3734 Network_Notes index...")

    # Create _Index section in notebook 2
    idx_id = com_client.open_hierarchy("_Index.one", NB2_ID)
    print(f"  _Index section in NB2: {idx_id}")

    b = f'<span {H1}>3734 Network_Notes -- Master Index</span>{BR}'
    b += f'<span {GRAY}><i>Index of all sections and pages in this notebook.</i></span>{BR2}'

    b += f'<span {H2}>pictureCollages (3 pages)</span>{BR}'
    b += f'{INDENT}2 Untitled pages (photo collages from 2018){BR}'
    b += f'{INDENT}Athena\'s cards (2021){BR2}'

    b += f'<span {H2}>Misc_Tech_stuff (14 pages)</span>{BR}'
    b += f'{INDENT}Acronis info -- Backup software{BR}'
    b += f'{INDENT}USB drive notes -- USB configuration{BR}'
    b += f'{INDENT}HD_homerun -- TV tuner device{BR}'
    b += f'{INDENT}Docker -- Docker reference (updated 2026-02-05){BR}'
    b += f'{INDENT}{INDENT}Open webui -- Docker compose for Open WebUI{BR}'
    b += f'{INDENT}Arcana Machina -- Tech magic reference{BR}'
    b += f'{INDENT}{INDENT}Windows Sacra -- Windows sacred knowledge{BR}'
    b += f'{INDENT}{INDENT}Linux Sacra -- Centos -- Python Stuff -- FAUXMO{BR}'
    b += f'{INDENT}Spark40 -- Guitar amp{BR}'
    b += f'{INDENT}Windows genera -- General Windows tips{BR}'
    b += f'{INDENT}Web Scraping -- Scraping techniques{BR2}'

    b += f'<span {H2}>AirQuality (2 pages)</span>{BR}'
    b += f'{INDENT}TVOCs -- Total Volatile Organic Compounds{BR}'
    b += f'{INDENT}CO2 -- Carbon dioxide monitoring{BR2}'

    b += f'<span {H2}>infrastructure_tech (10 pages)</span>{BR}'
    b += f'{INDENT}Truenas -- TrueNAS config (updated 2026-02-16){BR}'
    b += f'{INDENT}Splashtop info -- Remote desktop{BR}'
    b += f'{INDENT}Home Assistant -- Smart home (updated 2026-01-28){BR}'
    b += f'{INDENT}{INDENT}Tasmota -- IoT device flashing{BR}'
    b += f'{INDENT}Megatron -- Workstation notes{BR}'
    b += f'{INDENT}Legacy network info -- Old network config{BR}'
    b += f'{INDENT}OctoPrint -- 3D printer server{BR}'
    b += f'{INDENT}Mine Craft Pi -- Minecraft on RPi{BR}'
    b += f'{INDENT}PullyPi -- Raspberry Pi project{BR}'
    b += f'{INDENT}{INDENT}Element14 RPi Node Red Alexa -- IoT automation{BR2}'

    b += f'<span {H2}>network stuff (14 pages)</span>{BR}'
    b += f'{INDENT}Unifi info (updated 2026-01-28) -- Controller config{BR}'
    b += f'{INDENT}{INDENT}Url codes, Udm commands, ESXI/RHEL, Commands{BR}'
    b += f'{INDENT}{INDENT}Unifi controller stop service, Ap led flash codes{BR}'
    b += f'{INDENT}Windows firewall Track activity in log{BR}'
    b += f'{INDENT}USG firewall notes{BR}'
    b += f'{INDENT}Gaming configs{BR}'
    b += f'{INDENT}Windows networking{BR}'
    b += f'{INDENT}NetDuma -- Gaming router config{BR}'
    b += f'{INDENT}Pi Hole -- DNS ad blocker{BR2}'

    b += f'<span {H2}>ML_Stories (1 page)</span>{BR}'
    b += f'{INDENT}Huggingface_stories -- HuggingFace content from 2023{BR}'

    create_page(idx_id, "3734 Network_Notes -- Master Index", b)
    print("  Done")


# =====================================================================
# Main
# =====================================================================

if __name__ == "__main__":
    print("=" * 60)
    print("OneNote Notebook Organizer -- Megatron2")
    print("=" * 60)
    print()

    create_master_index()
    create_networking_index()
    create_programming_index()
    create_cybertron_index()
    create_career_index()
    create_ai_ml_index()
    create_quick_notes_index()
    create_nb2_index()

    print()
    print("=" * 60)
    print("DONE. All index pages created.")
    print("=" * 60)
